project_id = "umtqmhzzxbfvokbiwsmr"

[functions.check-admin]
verify_jwt = false

[functions.qa-ai-answer]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.bot-chat]
verify_jwt = false

[functions.mentor-chat]
verify_jwt = false

[functions.admin-insights]
verify_jwt = false

[functions.mentor-analyze]
verify_jwt = false

[functions.website-submit-lead]
verify_jwt = false

[functions.mentor-score]
verify_jwt = false

[functions.admin-analytics]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-mentor-conversations]
verify_jwt = false

[functions.send-trial-reminders]
verify_jwt = false

[functions.signup-send-otp]
verify_jwt = false

[functions.signup-verify-otp]
verify_jwt = false

