project_id = "umtqmhzzxbfvokbiwsmr"

[functions.check-admin]
verify_jwt = false

[functions.qa-ai-answer]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.bot-chat]
verify_jwt = false

[functions.mentor-chat]
verify_jwt = false

[functions.admin-insights]
verify_jwt = false

[functions.mentor-analyze]
verify_jwt = false

[functions.website-submit-lead]
verify_jwt = false
