import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "he";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "nav.home": "Home",
    "nav.about": "About",
    "nav.bots": "AI Assistants",
    "nav.contact": "Contact",
    "nav.contents": "Contents",
    "nav.portal": "Student Portal",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.dashboard": "Dashboard",

    // Dashboard
    "dashboard.welcome": "Welcome!",
    "dashboard.subtitle": "Track your progress and continue learning",
    "dashboard.myProgress": "My Progress",
    "dashboard.totalLessons": "Total Lessons",
    "dashboard.watchedLessons": "Completed",
    "dashboard.remainingLessons": "Remaining",
    "dashboard.nextStep": "Your next step",
    "dashboard.continue": "Continue",
    "dashboard.allCompleted": "All lessons completed!",
    "dashboard.congratulations": "Amazing work! You've completed the entire course.",
    "dashboard.myLessons": "My Lessons",
    "dashboard.lesson": "Lesson",
    "dashboard.admin.title": "General Statistics",
    "dashboard.admin.totalUsers": "Total Users",
    "dashboard.admin.activeUsers": "Active (7 days)",
    "dashboard.admin.completionRate": "Completion Rate",
    "dashboard.admin.progressByLesson": "Progress by Lesson",
    "dashboard.admin.recentUsers": "Recent Users",
    "dashboard.admin.user": "User",
    "dashboard.admin.progress": "Progress",
    "dashboard.admin.lastActivity": "Last Activity",
    "dashboard.admin.noUsers": "No users yet",
    "dashboard.admin.anonymous": "Anonymous",
    "dashboard.admin.previous": "Previous",
    "dashboard.admin.next": "Next",
    "dashboard.admin.page": "Page",

    // Hero
    "hero.title": "Market Your Practice with Authenticity",
    "hero.subtitle": "Build a thriving private practice without anxiety or compromising who you are",
    "hero.cta": "Get Free Resources",

    // Benefits / Transformation
    "benefits.label": "The Transformation",
    "benefits.title": "Your Results",
    "benefits.subtitle": "Mental and practical outcomes that transform your practice and life",
    "benefits.item1.title": "Unshakable Professional Confidence",
    "benefits.item1.desc":
      "Feel the true value of your work and project it naturally in marketing and therapy sessions. No more second-guessing your worth.",
    "benefits.item2.title": "Consistent Flow of Ideal Patients",
    "benefits.item2.desc":
      "No more relying on luck. A predictable system that fills your clinic with patients you love to treat.",
    "benefits.item3.title": "Financial Freedom & Zero Burnout",
    "benefits.item3.desc":
      "Earn what you deserve while maintaining professional boundaries and personal well-being. Work less, earn more, live better.",

    // Bots
    "bots.title": "AI Assistants for Therapists",
    "bots.subtitle": "Powerful tools designed specifically to help you grow your practice",
    "bots.niche.title": "Niche Finder Bot",
    "bots.niche.desc": "Discover your unique therapeutic niche and ideal client profile through guided exploration",
    "bots.strategy.title": "Strategy Planner Bot",
    "bots.strategy.desc": "Create a personalized marketing strategy that aligns with your values and schedule",
    "bots.content.title": "Content Creator Bot",
    "bots.content.desc": "Generate authentic content ideas that showcase your expertise and attract clients",
    "bots.cta": "Try Now",
    "bots.teaser": "Want to discover our digital assistants?",
    "bots.teaserLink": "Learn more",

    // How It Works
    "howItWorks.label": "The Turning Point Program",
    "howItWorks.title": "4 Steps to a Thriving Practice",
    "howItWorks.subtitle": "A structured journey from uncertainty to professional confidence",
    "howItWorks.step1.title": "Precise Professional Identity",
    "howItWorks.step1.desc":
      "Transition from 'amateur' to 'pro' by defining your ideal patient and unique expertise. Learn to present yourself in a way that attracts the right clients.",
    "howItWorks.step2.title": "Referral & Lead Mechanism",
    "howItWorks.step2.desc":
      "Build a systematic flow of inquiries through professional networking. Overcome 'imposter syndrome' and create consistent referral relationships.",
    "howItWorks.step3.title": "From Inquiry to Patient",
    "howItWorks.step3.desc":
      "Master the 'matching call' with confidence. Learn to lead potential patients to a committed therapeutic process professionally.",
    "howItWorks.step4.title": "Financial Stability & Boundaries",
    "howItWorks.step4.desc":
      "Profitable pricing, overcoming money blocks, and setting clear boundaries around cancellations and payments.",

    // CTA
    "cta.title": "Ready to grow your practice authentically?",
    "cta.button": "Discover if it's right for me",

    // Form
    "form.title": "Get Free Marketing Resources",
    "form.subtitle": "Join our community and receive practical tools to grow your practice authentically",
    "form.name": "Full Name",
    "form.email": "Email Address",
    "form.phone": "Mobile Number",
    "form.submit": "Get Free Materials",
    "form.privacy": "We respect your privacy. Unsubscribe anytime.",

    // Footer
    "footer.tagline": "Empowering therapists to grow with authenticity",
    "footer.rights": "All rights reserved",

    // Contents
    "contents.title": "Resources & Articles",
    "contents.subtitle": "Insights and tools to help you grow your practice",
    "contents.empty": "No content available yet",
    "contents.readMore": "Read More",
    "contents.back": "Back to Contents",
    "contents.admin.add": "Add Content",
    "contents.admin.edit": "Edit",
    "contents.admin.delete": "Delete",
    "contents.admin.cancel": "Cancel",
    "contents.admin.save": "Save",
    "contents.admin.saving": "Saving...",
    "contents.admin.saveSuccess": "Content saved successfully",
    "contents.admin.saveError": "Error saving content",
    "contents.admin.deleteConfirm": "Delete Content?",
    "contents.admin.deleteWarning": "This action cannot be undone.",
    "contents.admin.deleteSuccess": "Content deleted successfully",
    "contents.admin.deleteError": "Error deleting content",
    "contents.form.title": "Title",
    "contents.form.titlePlaceholder": "Enter title...",
    "contents.form.content": "Content",
    "contents.form.contentPlaceholder": "Enter content...",
    "contents.form.language": "Language",
    "contents.form.category": "Category",
    "contents.form.selectCategory": "Select category...",
    "contents.form.status": "Status",
    "contents.form.excerpt": "Excerpt",
    "contents.form.excerptPlaceholder": "Short summary (optional)...",
    "contents.form.featuredImage": "Featured Image",
    "contents.form.uploadImage": "Click to upload image",
    "contents.status.draft": "Draft",
    "contents.status.published": "Published",
    "contents.status.archived": "Archived",
    "contents.admin.saveDraft": "Save Draft",
    "contents.admin.publish": "Publish",
    "contents.allCategories": "All Topics",
    "contents.searchPlaceholder": "Search articles...",
    "contents.resultsCount": "{count} articles found",
    "contents.noResults": "No articles match your search",
    "contents.editor.enterUrl": "Enter URL:",
    "contents.editor.imageUploaded": "Image uploaded successfully",
    "contents.editor.imageUploadError": "Error uploading image",

    // Auth
    "auth.loginTitle": "Welcome Back",
    "auth.loginSubtitle": "Sign in to your account",
    "auth.signupTitle": "Create Account",
    "auth.signupSubtitle": "Join our community of therapists",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.loginButton": "Sign In",
    "auth.signupButton": "Create Account",
    "auth.loading": "Loading...",
    "auth.noAccount": "Don't have an account? Sign up",
    "auth.hasAccount": "Already have an account? Sign in",
    "auth.loginSuccess": "Welcome back!",
    "auth.signupSuccess": "Account created! Check your email to confirm.",
    "auth.alreadyRegistered": "This email is already registered",
    "auth.forgotPassword": "Forgot your password?",
    "auth.forgotTitle": "Reset Password",
    "auth.forgotSubtitle": "Enter your email to receive a reset link",
    "auth.sendResetLink": "Send Reset Link",
    "auth.resetSent": "Check your email for the reset link",
    "auth.resetTitle": "Set New Password",
    "auth.resetSubtitle": "Enter your new password",
    "auth.newPassword": "New Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.updatePassword": "Update Password",
    "auth.passwordUpdated": "Password updated successfully!",
    "auth.passwordMismatch": "Passwords don't match",
    "auth.backToLogin": "Back to login",
    "auth.preparingReset": "Preparing password reset...",
    "auth.sessionError": "Error setting up session. Please try the reset link again.",
    "auth.resetLinkInvalidTitle": "Link Invalid or Expired",
    "auth.resetLinkInvalidBody": "This reset link is no longer valid. It may have expired or already been used.",
    "auth.requestNewResetLink": "Request New Link",
    // Portal
    "portal.title": "Student Portal",
    "portal.noAccess": "Access Denied",
    "portal.accessDescription":
      "You don't have access to this area. Please contact the administrator if you believe this is an error.",
    "portal.lessons": "Lessons",
    "portal.noLessons": "No lessons available yet",
    "portal.video": "Video",
    "portal.videos": "Videos",
    "portal.exercise": "Exercise",
    "portal.presentation": "Presentation",
    "portal.files": "Files",
    "portal.download": "Download",
    "portal.downloadError": "Error downloading file",
    "portal.watch": "Watch",
    "portal.back": "Back",
    "portal.lessonNotFound": "Lesson not found",
    "portal.noVideos": "No videos available",
    "portal.noFiles": "No files available",
    "portal.qa": "Q&A",
    "portal.askQuestion": "Ask a Question",
    "portal.questionPlaceholder": "Type your question here...",
    "portal.questionPrivate": "Private question (only admin sees)",
    "portal.questionPublic": "Public question (visible to all)",
    "portal.submit": "Submit",
    "portal.questionSubmitted": "Question submitted successfully",
    "portal.questionError": "Error submitting question",
    "portal.noQuestions": "No questions yet",
    "portal.answered": "Answered",
    "portal.noAnswer": "Not answered yet",
    "portal.public": "Public",
    "portal.private": "Private",
    "portal.admin.title": "Portal Management",
    "portal.admin.addLesson": "Add Lesson",
    "portal.admin.description": "Description",
    "portal.admin.descriptionPlaceholder": "Enter lesson description...",
    "portal.admin.lessonAdded": "Lesson added successfully",
    "portal.admin.lessonError": "Error adding lesson",
    "portal.admin.existingLessons": "Existing Lessons",
    "portal.admin.lessonDeleted": "Lesson deleted",
    "portal.admin.deleteError": "Error deleting",
    "portal.admin.uploadFile": "Upload File",
    "portal.admin.selectLesson": "Select Lesson",
    "portal.admin.selectLessonPlaceholder": "Choose a lesson...",
    "portal.admin.fileType": "File Type",
    "portal.admin.selectFile": "Select File",
    "portal.admin.uploading": "Uploading...",
    "portal.admin.fileUploaded": "File uploaded successfully",
    "portal.admin.fileError": "Error uploading file",
    "portal.admin.unanswered": "unanswered",
    "portal.admin.yourAnswer": "Your answer",
    "portal.admin.answerPlaceholder": "Type your answer...",
    "portal.admin.answer": "Answer",
    "portal.admin.answerSaved": "Answer saved",
    "portal.admin.answerError": "Error saving answer",
    "portal.admin.addResource": "Add",
    "portal.admin.addVideo": "Add Recording",
    "portal.admin.addPresentation": "Add Presentation",
    "portal.admin.addWorksheet": "Add Worksheet",
    "portal.admin.presentations": "Presentations",
    "portal.admin.worksheets": "Worksheets",
    "portal.admin.noResources": "None yet",
    "portal.admin.resourceTitle": "Title",
    "portal.admin.dragToReorder": "Drag to reorder",
    "portal.admin.resourceDeleted": "Resource deleted",
    "portal.admin.orderUpdated": "Order updated",
    "portal.admin.videoSource": "Video source",
    "portal.admin.youtubeLink": "YouTube link",
    "portal.admin.vimeoLink": "Vimeo link",
    "portal.admin.zoomLink": "Zoom recording",
    "portal.admin.enterUrl": "Enter link",
    "portal.admin.invalidUrl": "Invalid link",
    "portal.admin.validUrl": "Valid link",
    "portal.openRecording": "Open Recording",
    "portal.zoomRecording": "Zoom Recording",
    "portal.zoomRecordingMessage": "Zoom recordings open in a new window",
    "portal.invalidVideoUrl": "Invalid video URL",
    "portal.video.zoomTitle": "Video Recording",
    "portal.video.zoomDescription": "This recording opens in a separate window for optimal viewing",
    "portal.video.watchButton": "Watch Recording",
    "portal.admin.zoomWarning":
      "Zoom links open outside the system. For embedded playback, upload an MP4 file or use YouTube/Vimeo.",
    "portal.admin.recommended": "Recommended",

    // Media Library
    "media.title": "Media Library",
    "media.upload": "Upload New",
    "media.search": "Search...",
    "media.filterByType": "Filter by type",
    "media.allTypes": "All Types",
    "media.typeVideo": "Video",
    "media.typeDocument": "Document",
    "media.typePresentation": "Presentation",
    "media.typeAudio": "Audio",
    "media.typeLink": "Link",
    "media.noMedia": "No media yet",
    "media.columnTitle": "Title",
    "media.columnType": "Type",
    "media.columnSource": "Source",
    "media.columnDuration": "Duration",
    "media.columnUsage": "Usage",
    "media.columnActions": "Actions",
    "media.sourceFile": "File",
    "media.usedInLessons": "In {count} lessons",
    "media.usedInLessonsLabel": "Used in lessons",
    "media.deleteConfirm": "Delete Media?",
    "media.deleteWarning": "This action cannot be undone.",
    "media.deleteWarningUsed": "This media is used in {count} lessons. Deleting it will remove it from all lessons.",
    "media.edit": "Edit Media",
    "media.description": "Description",
    "media.descriptionPlaceholder": "Add notes about this media (admin only)...",
    "media.selectFromLibrary": "Select from Library",
    "media.uploadNew": "Upload New",
    "media.addToLesson": "Add to Lesson",
    "media.addedToLesson": "Added to lesson",
    "media.removeFromLesson": "Remove from lesson",
    "media.removedFromLesson": "Removed from lesson",
    "media.selectedCount": "{count} selected",
  },
  he: {
    // Header
    "nav.home": "בית",
    "nav.about": "אודות",
    "nav.bots": "עוזרי AI",
    "nav.contact": "צור קשר",
    "nav.contents": "על שפת הקליניקה",
    "nav.portal": "נקודת המפנה",
    "nav.login": "התחברות",
    "nav.logout": "התנתקות",
    "nav.dashboard": "דשבורד",

    // Dashboard
    "dashboard.welcome": "ברוכה הבאה!",
    "dashboard.subtitle": "עקבי אחרי ההתקדמות שלך והמשיכי ללמוד",
    "dashboard.myProgress": "ההתקדמות שלי",
    "dashboard.totalLessons": "סה״כ שיעורים",
    "dashboard.watchedLessons": "הושלמו",
    "dashboard.remainingLessons": "נותרו",
    "dashboard.nextStep": "הצעד הבא שלך",
    "dashboard.continue": "המשיכי",
    "dashboard.allCompleted": "כל השיעורים הושלמו!",
    "dashboard.congratulations": "עבודה מדהימה! סיימת את כל הקורס.",
    "dashboard.myLessons": "השיעורים שלי",
    "dashboard.lesson": "שיעור",
    "dashboard.admin.title": "סטטיסטיקות כלליות",
    "dashboard.admin.totalUsers": "סה״כ משתמשים",
    "dashboard.admin.activeUsers": "פעילים (7 ימים)",
    "dashboard.admin.completionRate": "אחוז השלמה",
    "dashboard.admin.progressByLesson": "התקדמות לפי שיעור",
    "dashboard.admin.recentUsers": "משתמשים אחרונים",
    "dashboard.admin.user": "משתמש",
    "dashboard.admin.progress": "התקדמות",
    "dashboard.admin.lastActivity": "פעילות אחרונה",
    "dashboard.admin.noUsers": "אין משתמשים עדיין",
    "dashboard.admin.anonymous": "אנונימי",
    "dashboard.admin.previous": "הקודם",
    "dashboard.admin.next": "הבא",
    "dashboard.admin.page": "עמוד",

    // Hero
    "hero.title": "הדרך שלך לקליניקה יציבה ומבוקשת",
    "hero.subtitle": " איך ליצור קליניקה שמתאימה לך",
    "hero.cta": "הצטרפו לקהילת על שפת הקליניקה",

    // Benefits / Transformation
    "benefits.label": "הטרנספורמציה",
    "benefits.title": "התוצאות שלכם",
    "benefits.subtitle": "תוצאות רגשיות ומעשיות שמשנות את הקליניקה ואת הביטחון המקצועי שלכם",
    "benefits.item1.title": "ביסוס הביטחון העצמי המקצועי - להכיר בערך שלי כמטפל  ",
    "benefits.item1.desc": "להרגיש את הערך האמיתי של הטיפול שלכם ולהקרין אותו החוצה באופן טבעי",
    "benefits.item2.title": "זרם עקבי של מטופלים מתאימים",
    "benefits.item2.desc":
      " לדעת שיש מטופלים שממתינים לכם. מערכת יציבה שממלאה את הקליניקה במטופלים שאתם אוהבים לטפל בהם",
    "benefits.item3.title": "חופש לטפל בלי המתח הכלכלי",
    "benefits.item3.desc":
      "להרוויח את מה שמגיע לכם תוך שמירה על גבולות מקצועיים ורווחה אישית. לעבוד פחות, להרוויח יותר, לחיות טוב יותר.",

    // Bots
    "bots.title": "עוזרי AI למטפלים",
    "bots.subtitle": "כלים חכמים שתוכננו במיוחד לעזור לכם לצמוח בפרקטיקה",
    "bots.niche.title": "בוט מציאת נישה",
    "bots.niche.desc": "גלו את הנישה הטיפולית הייחודית שלכם ואת פרופיל הלקוח האידיאלי באמצעות חקירה מודרכת",
    "bots.strategy.title": "בוט תכנון אסטרטגיה",
    "bots.strategy.desc": "צרו אסטרטגיית שיווק מותאמת אישית שמתאימה לערכים ולזמן שלכם",
    "bots.content.title": "בוט יצירת תוכן",
    "bots.content.desc": "הפיקו רעיונות תוכן אותנטיים שמציגים את המומחיות שלכם ומושכים לקוחות",
    "bots.cta": "נסו עכשיו",
    "bots.teaser": "רוצים לגלות את העוזרים הדיגיטליים שלנו?",
    "bots.teaserLink": "למידע נוסף",

    // How It Works
    "howItWorks.label": "תוכנית נקודת המפנה",
    "howItWorks.title": "4 שלבים לקליניקה משגשגת",
    "howItWorks.subtitle": "מסע מובנה מחוסר ודאות לביטחון מקצועי",
    "howItWorks.step1.title": "דיוק הזהות המקצועית",
    "howItWorks.step1.desc":
      "מעבר מ'חובבן' ל'מקצוען' דרך הגדרת המטופל האידיאלי והמומחיות הייחודית. ללמוד להציג את עצמנו בצורה שמושכת את הלקוחות הנכונים.",
    "howItWorks.step2.title": "מנגנון הפניות ולידים",
    "howItWorks.step2.desc":
      "בניית זרם פניות שיטתי דרך קשרים מקצועיים. התמודדות עם 'תסמונת המתחזה' ויצירת קשרי הפניות עקביים.",
    "howItWorks.step3.title": "ממתעניין למטופל",
    "howItWorks.step3.desc":
      "שליטה ב'שיחת ההתאמה' מתוך ביטחון. ללמוד להוביל מטופלים פוטנציאליים לתהליך טיפולי מחויב בצורה מקצועית.",
    "howItWorks.step4.title": "יציבות כלכלית וגבולות",
    "howItWorks.step4.desc": "תמחור רווחי, התגברות על חסמים סביב כסף, והצבת גבולות ברורים סביב ביטולים ותשלומים.",

    // CTA
    "cta.title": "הצטרפו לקהילת על שפת הקליניקה",
    "cta.button": "לגלות אם זה מתאים לי",

    // Form
    "form.title": "איך מבססים קליניקה מצליחה",
    "form.subtitle": "הצטרפו לקהילה שלנו וקבלו כלים עיוניים, מעשיים,ורגשיים להצמיח את הקליניקה שלכם",
    "form.name": "שם מלא",
    "form.email": "כתובת אימייל",
    "form.phone": "מספר נייד",
    "form.submit": "אני רוצה להצטרף",
    "form.privacy": "אנחנו מכבדים את הפרטיות שלכם. ניתן לבטל בכל עת.",

    // Footer
    "footer.tagline": "מעצימים מטפלים לצמוח באותנטיות",
    "footer.rights": "כל הזכויות שמורות",

    // Contents
    "contents.title": "משאבים ומאמרים",
    "contents.subtitle": "תובנות וכלים שיעזרו לכם לצמוח בפרקטיקה",
    "contents.empty": "אין תכנים זמינים עדיין",
    "contents.readMore": "קראו עוד",
    "contents.back": "חזרה לתכנים",
    "contents.admin.add": "הוסף תוכן",
    "contents.admin.edit": "ערוך",
    "contents.admin.delete": "מחק",
    "contents.admin.cancel": "ביטול",
    "contents.admin.save": "שמור",
    "contents.admin.saving": "שומר...",
    "contents.admin.saveSuccess": "התוכן נשמר בהצלחה",
    "contents.admin.saveError": "שגיאה בשמירת התוכן",
    "contents.admin.deleteConfirm": "למחוק את התוכן?",
    "contents.admin.deleteWarning": "לא ניתן לבטל פעולה זו.",
    "contents.admin.deleteSuccess": "התוכן נמחק בהצלחה",
    "contents.admin.deleteError": "שגיאה במחיקת התוכן",
    "contents.form.title": "כותרת",
    "contents.form.titlePlaceholder": "הזינו כותרת...",
    "contents.form.content": "תוכן",
    "contents.form.contentPlaceholder": "הזינו תוכן...",
    "contents.form.language": "שפה",
    "contents.form.category": "קטגוריה",
    "contents.form.selectCategory": "בחרו קטגוריה...",
    "contents.form.status": "סטטוס",
    "contents.form.excerpt": "תקציר",
    "contents.form.excerptPlaceholder": "סיכום קצר (אופציונלי)...",
    "contents.form.featuredImage": "תמונה ראשית",
    "contents.form.uploadImage": "לחצו להעלאת תמונה",
    "contents.status.draft": "טיוטה",
    "contents.status.published": "פורסם",
    "contents.status.archived": "ארכיון",
    "contents.admin.saveDraft": "שמור כטיוטה",
    "contents.admin.publish": "פרסם",
    "contents.allCategories": "כל הנושאים",
    "contents.searchPlaceholder": "חיפוש מאמרים...",
    "contents.resultsCount": "נמצאו {count} מאמרים",
    "contents.noResults": "לא נמצאו מאמרים התואמים לחיפוש",
    "contents.editor.enterUrl": "הזינו קישור:",
    "contents.editor.imageUploaded": "התמונה הועלתה בהצלחה",
    "contents.editor.imageUploadError": "שגיאה בהעלאת התמונה",

    // Auth
    "auth.loginTitle": "נקודת המפנה",
    "auth.loginSubtitle": "התחברו לחשבון שלכם",
    "auth.signupTitle": "יצירת חשבון",
    "auth.signupSubtitle": "הצטרפו לקהילת המטפלים שלנו",
    "auth.email": "אימייל",
    "auth.password": "סיסמה",
    "auth.loginButton": "התחברות",
    "auth.signupButton": "יצירת חשבון",
    "auth.loading": "טוען...",
    "auth.noAccount": "אין לכם חשבון? הירשמו",
    "auth.hasAccount": "כבר יש לכם חשבון? התחברו",
    "auth.loginSuccess": "ברוכים השבים!",
    "auth.signupSuccess": "החשבון נוצר! בדקו את האימייל לאישור.",
    "auth.alreadyRegistered": "האימייל הזה כבר רשום",
    "auth.forgotPassword": "שכחת את הסיסמה?",
    "auth.forgotTitle": "איפוס סיסמה",
    "auth.forgotSubtitle": "הזינו את האימייל שלכם לקבלת קישור איפוס",
    "auth.sendResetLink": "שלח קישור איפוס",
    "auth.resetSent": "בדקו את האימייל לקבלת הקישור",
    "auth.resetTitle": "הגדרת סיסמה חדשה",
    "auth.resetSubtitle": "הזינו את הסיסמה החדשה שלכם",
    "auth.newPassword": "סיסמה חדשה",
    "auth.confirmPassword": "אישור סיסמה",
    "auth.updatePassword": "עדכון סיסמה",
    "auth.passwordUpdated": "הסיסמה עודכנה בהצלחה!",
    "auth.passwordMismatch": "הסיסמאות לא תואמות",
    "auth.backToLogin": "חזרה להתחברות",
    "auth.preparingReset": "מכינים את האפשרות לאיפוס סיסמה...",
    "auth.sessionError": "שגיאה בהגדרת הסשן. נסו את הקישור שוב.",
    "auth.resetLinkInvalidTitle": "הקישור לא תקין או פג תוקף",
    "auth.resetLinkInvalidBody": "קישור האיפוס כבר לא בתוקף. ייתכן שפג תוקפו או שכבר נוצל.",
    "auth.requestNewResetLink": "בקש קישור חדש",

    // Portal
    "portal.title": "אזור התלמידים",
    "portal.noAccess": "אין גישה",
    "portal.accessDescription": "אין לך גישה לאזור זה. אנא פנה למנהל אם אתה מאמין שזו שגיאה.",
    "portal.lessons": "שיעורים",
    "portal.noLessons": "אין שיעורים עדיין",
    "portal.video": "וידאו",
    "portal.videos": "הקלטות וידאו",
    "portal.exercise": "תרגיל",
    "portal.presentation": "מצגת",
    "portal.files": "קבצים",
    "portal.download": "הורד",
    "portal.downloadError": "שגיאה בהורדת הקובץ",
    "portal.watch": "צפה",
    "portal.back": "חזרה",
    "portal.lessonNotFound": "השיעור לא נמצא",
    "portal.noVideos": "אין הקלטות וידאו",
    "portal.noFiles": "אין קבצים",
    "portal.qa": "שאלות ותשובות",
    "portal.askQuestion": "שאל שאלה",
    "portal.questionPlaceholder": "כתוב את השאלה שלך כאן...",
    "portal.questionPrivate": "שאלה פרטית (רק האדמין רואה)",
    "portal.questionPublic": "שאלה ציבורית (גלויה לכולם)",
    "portal.submit": "שלח",
    "portal.questionSubmitted": "השאלה נשלחה בהצלחה",
    "portal.questionError": "שגיאה בשליחת השאלה",
    "portal.noQuestions": "אין שאלות עדיין",
    "portal.answered": "נענתה",
    "portal.noAnswer": "טרם נענתה",
    "portal.public": "ציבורי",
    "portal.private": "פרטי",
    "portal.admin.title": "ניהול אזור תלמידים",
    "portal.admin.addLesson": "הוסף שיעור",
    "portal.admin.description": "תיאור",
    "portal.admin.descriptionPlaceholder": "הזן תיאור לשיעור...",
    "portal.admin.lessonAdded": "השיעור נוסף בהצלחה",
    "portal.admin.lessonError": "שגיאה בהוספת שיעור",
    "portal.admin.existingLessons": "שיעורים קיימים",
    "portal.admin.lessonDeleted": "השיעור נמחק",
    "portal.admin.deleteError": "שגיאה במחיקה",
    "portal.admin.uploadFile": "העלה קובץ",
    "portal.admin.selectLesson": "בחר שיעור",
    "portal.admin.selectLessonPlaceholder": "בחר שיעור...",
    "portal.admin.fileType": "סוג קובץ",
    "portal.admin.selectFile": "בחר קובץ",
    "portal.admin.uploading": "מעלה...",
    "portal.admin.fileUploaded": "הקובץ הועלה בהצלחה",
    "portal.admin.fileError": "שגיאה בהעלאת הקובץ",
    "portal.admin.unanswered": "ללא תשובה",
    "portal.admin.yourAnswer": "תשובתך",
    "portal.admin.answerPlaceholder": "כתוב את התשובה שלך...",
    "portal.admin.answer": "ענה",
    "portal.admin.answerSaved": "התשובה נשמרה",
    "portal.admin.answerError": "שגיאה בשמירת התשובה",
    "portal.admin.addResource": "הוסף",
    "portal.admin.addVideo": "הוסף הקלטה",
    "portal.admin.addPresentation": "הוסף מצגת",
    "portal.admin.addWorksheet": "הוסף דף עבודה",
    "portal.admin.presentations": "מצגות",
    "portal.admin.worksheets": "דפי עבודה",
    "portal.admin.noResources": "אין עדיין",
    "portal.admin.resourceTitle": "כותרת",
    "portal.admin.dragToReorder": "גרור לשינוי סדר",
    "portal.admin.resourceDeleted": "המשאב נמחק",
    "portal.admin.orderUpdated": "הסדר עודכן",
    "portal.admin.videoSource": "מקור הוידאו",
    "portal.admin.youtubeLink": "קישור YouTube",
    "portal.admin.vimeoLink": "קישור Vimeo",
    "portal.admin.zoomLink": "הקלטת Zoom",
    "portal.admin.enterUrl": "הכניסי קישור",
    "portal.admin.invalidUrl": "קישור לא תקין",
    "portal.admin.validUrl": "קישור תקין",
    "portal.openRecording": "פתח הקלטה",
    "portal.zoomRecording": "הקלטת Zoom",
    "portal.zoomRecordingMessage": "הקלטות Zoom נפתחות בחלון חדש",
    "portal.invalidVideoUrl": "קישור וידאו לא תקין",
    "portal.video.zoomTitle": "הקלטת הרצאה",
    "portal.video.zoomDescription": "הקלטה זו נפתחת בחלון נפרד לחוויית צפייה מיטבית",
    "portal.video.watchButton": "צפייה בהקלטה",
    "portal.admin.zoomWarning":
      "קישורי Zoom נפתחים מחוץ למערכת. להטמעה מלאה, העלי קובץ וידאו או השתמשי ב-YouTube/Vimeo.",
    "portal.admin.recommended": "מומלץ",

    // Media Library
    "media.title": "ספריית מדיה",
    "media.upload": "העלה חדש",
    "media.search": "חיפוש...",
    "media.filterByType": "סנן לפי סוג",
    "media.allTypes": "כל הסוגים",
    "media.typeVideo": "וידאו",
    "media.typeDocument": "מסמך",
    "media.typePresentation": "מצגת",
    "media.typeAudio": "אודיו",
    "media.typeLink": "לינק",
    "media.noMedia": "אין מדיה עדיין",
    "media.columnTitle": "כותרת",
    "media.columnType": "סוג",
    "media.columnSource": "מקור",
    "media.columnDuration": "אורך",
    "media.columnUsage": "שימוש",
    "media.columnActions": "פעולות",
    "media.sourceFile": "קובץ",
    "media.usedInLessons": "ב-{count} שיעורים",
    "media.usedInLessonsLabel": "נמצא בשיעורים",
    "media.deleteConfirm": "למחוק מדיה?",
    "media.deleteWarning": "לא ניתן לבטל פעולה זו.",
    "media.deleteWarningUsed": "המדיה בשימוש ב-{count} שיעורים. מחיקה תסיר אותה מכל השיעורים.",
    "media.edit": "עריכת מדיה",
    "media.description": "תיאור",
    "media.descriptionPlaceholder": "הוסף הערות על מדיה זו (לאדמין בלבד)...",
    "media.selectFromLibrary": "בחר מהספרייה",
    "media.uploadNew": "העלה חדש",
    "media.addToLesson": "הוסף לשיעור",
    "media.addedToLesson": "נוסף לשיעור",
    "media.removeFromLesson": "הסר משיעור",
    "media.removedFromLesson": "הוסר מהשיעור",
    "media.selectedCount": "{count} נבחרו",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("he");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === "he";

  return <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
