import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "he";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "nav.home": "Home",
    "nav.about": "About",
    "nav.bots": "AI Assistants",
    "nav.contact": "Contact",
    "nav.contents": "Contents",
    "nav.portal": "Student Portal",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.dashboard": "Dashboard",

    // Dashboard
    "dashboard.welcome": "Welcome!",
    "dashboard.subtitle": "Track your progress and continue learning",
    "dashboard.myProgress": "My Progress",
    "dashboard.totalLessons": "Total Lessons",
    "dashboard.watchedLessons": "Completed",
    "dashboard.remainingLessons": "Remaining",
    "dashboard.nextStep": "Your next step",
    "dashboard.continue": "Continue",
    "dashboard.allCompleted": "All lessons completed!",
    "dashboard.congratulations": "Amazing work! You've completed the entire course.",
    "dashboard.myLessons": "My Lessons",
    "dashboard.lesson": "Lesson",
    "dashboard.admin.title": "General Statistics",
    "dashboard.admin.totalUsers": "Total Users",
    "dashboard.admin.activeUsers": "Active (7 days)",
    "dashboard.admin.completionRate": "Completion Rate",
    "dashboard.admin.progressByLesson": "Progress by Lesson",
    "dashboard.admin.recentUsers": "Recent Users",
    "dashboard.admin.user": "User",
    "dashboard.admin.progress": "Progress",
    "dashboard.admin.lastActivity": "Last Activity",
    "dashboard.admin.noUsers": "No users yet",
    "dashboard.admin.anonymous": "Anonymous",
    "dashboard.admin.previous": "Previous",
    "dashboard.admin.next": "Next",
    "dashboard.admin.page": "Page",

    // Hero
    "hero.title": "Market Your Practice with Authenticity",
    "hero.subtitle": "Build a thriving private practice without anxiety or compromising who you are",
    "hero.cta": "Get Free Resources",
    "hero.secondary_cta": "See How It Works",

    // How It Works
    "howItWorks.label": "The Process",
    "howItWorks.title": "Your Path to a Thriving Practice",
    "howItWorks.subtitle": "Four simple steps to transform your clinical practice",
    "howItWorks.step1.title": "Sign Up",
    "howItWorks.step1.desc": "Create your account and get instant access to all learning materials",
    "howItWorks.step2.title": "Learn",
    "howItWorks.step2.desc": "Watch video lessons and complete practical exercises at your own pace",
    "howItWorks.step3.title": "Get Support",
    "howItWorks.step3.desc": "Ask questions and receive personalized guidance from our experts",
    "howItWorks.step4.title": "Grow",
    "howItWorks.step4.desc": "Apply what you've learned and watch your practice flourish",

    // Benefits
    "benefits.label": "Why Choose Us",
    "benefits.title": "Grow Your Practice, Stay True to Yourself",
    "benefits.subtitle": "Our approach helps psychotherapists attract ideal clients while honoring their therapeutic values",
    "benefits.item1.title": "Find Your Niche",
    "benefits.item1.desc": "Discover what makes your practice unique and attracts clients who truly resonate with your approach",
    "benefits.item2.title": "Authentic Marketing",
    "benefits.item2.desc": "Learn marketing strategies that feel natural and align with your professional ethics",
    "benefits.item3.title": "Sustainable Growth",
    "benefits.item3.desc": "Build a stable practice with consistent client flow without burnout or overwhelm",

    // Testimonials
    "testimonials.label": "Success Stories",
    "testimonials.title": "What Therapists Are Saying",
    "testimonials.subtitle": "Join hundreds of therapists who transformed their practice",
    "testimonials.testimonial1.quote": "This course completely changed how I think about marketing my practice. I finally feel confident putting myself out there.",
    "testimonials.testimonial1.name": "Rachel K.",
    "testimonials.testimonial1.role": "Clinical Psychologist",
    "testimonials.testimonial2.quote": "The AI assistants are incredible. They helped me find my niche in just one session.",
    "testimonials.testimonial2.name": "Michael S.",
    "testimonials.testimonial2.role": "Marriage & Family Therapist",
    "testimonials.testimonial3.quote": "I went from 3 clients a week to a full caseload in just 2 months. Highly recommended!",
    "testimonials.testimonial3.name": "Aliza L.",
    "testimonials.testimonial3.role": "Art Therapist",

    // Features
    "features.label": "What's Included",
    "features.title": "Everything You Need to Succeed",
    "features.subtitle": "Comprehensive tools and resources designed for busy therapists",
    "features.videos.title": "Video Lessons",
    "features.videos.desc": "20+ hours of content",
    "features.exercises.title": "Practical Exercises",
    "features.exercises.desc": "Hands-on worksheets",
    "features.community.title": "Community Access",
    "features.community.desc": "Connect with peers",
    "features.ai.title": "AI Assistants",
    "features.ai.desc": "24/7 guidance",
    "features.support.title": "Personal Support",
    "features.support.desc": "Expert Q&A",
    "features.mobile.title": "Mobile Access",
    "features.mobile.desc": "Learn anywhere",

    // Bots
    "bots.title": "AI Assistants for Therapists",
    "bots.subtitle": "Powerful tools designed specifically to help you grow your practice",
    "bots.niche.title": "Niche Finder Bot",
    "bots.niche.desc": "Discover your unique therapeutic niche and ideal client profile through guided exploration",
    "bots.strategy.title": "Strategy Planner Bot",
    "bots.strategy.desc": "Create a personalized marketing strategy that aligns with your values and schedule",
    "bots.content.title": "Content Creator Bot",
    "bots.content.desc": "Generate authentic content ideas that showcase your expertise and attract clients",
    "bots.cta": "Try Now",
    "bots.teaser": "Want to discover our digital assistants?",
    "bots.teaserLink": "Learn more",

    // CTA
    "cta.title": "Ready to grow your practice authentically?",
    "cta.subtitle": "Join hundreds of therapists who have transformed their practice with our proven method",
    "cta.button": "Start Your Journey",
    "cta.secondaryButton": "Learn More",

    // Form
    "form.title": "Get Free Marketing Resources",
    "form.subtitle": "Join our community and receive practical tools to grow your practice authentically",
    "form.name": "Full Name",
    "form.email": "Email Address",
    "form.phone": "Mobile Number",
    "form.submit": "Get Free Materials",
    "form.privacy": "We respect your privacy. Unsubscribe anytime.",

    // Footer
    "footer.tagline": "Empowering therapists to grow with authenticity",
    "footer.rights": "All rights reserved",

    // Contents
    "contents.title": "Resources & Articles",
    "contents.subtitle": "Insights and tools to help you grow your practice",
    "contents.empty": "No content available yet",
    "contents.readMore": "Read More",
    "contents.back": "Back to Contents",
    "contents.admin.add": "Add Content",
    "contents.admin.edit": "Edit",
    "contents.admin.delete": "Delete",
    "contents.admin.cancel": "Cancel",
    "contents.admin.save": "Save",
    "contents.admin.saving": "Saving...",
    "contents.admin.saveSuccess": "Content saved successfully",
    "contents.admin.saveError": "Error saving content",
    "contents.admin.deleteConfirm": "Delete Content?",
    "contents.admin.deleteWarning": "This action cannot be undone.",
    "contents.admin.deleteSuccess": "Content deleted successfully",
    "contents.admin.deleteError": "Error deleting content",
    "contents.form.title": "Title",
    "contents.form.titlePlaceholder": "Enter title...",
    "contents.form.content": "Content",
    "contents.form.contentPlaceholder": "Enter content...",
    "contents.form.language": "Language",

    // Auth
    "auth.loginTitle": "Welcome Back",
    "auth.loginSubtitle": "Sign in to your account",
    "auth.signupTitle": "Create Account",
    "auth.signupSubtitle": "Join our community of therapists",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.loginButton": "Sign In",
    "auth.signupButton": "Create Account",
    "auth.loading": "Loading...",
    "auth.noAccount": "Don't have an account? Sign up",
    "auth.hasAccount": "Already have an account? Sign in",
    "auth.loginSuccess": "Welcome back!",
    "auth.signupSuccess": "Account created! Check your email to confirm.",
    "auth.alreadyRegistered": "This email is already registered",
    "auth.forgotPassword": "Forgot your password?",
    "auth.forgotTitle": "Reset Password",
    "auth.forgotSubtitle": "Enter your email to receive a reset link",
    "auth.sendResetLink": "Send Reset Link",
    "auth.resetSent": "Check your email for the reset link",
    "auth.resetTitle": "Set New Password",
    "auth.resetSubtitle": "Enter your new password",
    "auth.newPassword": "New Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.updatePassword": "Update Password",
    "auth.passwordUpdated": "Password updated successfully!",
    "auth.passwordMismatch": "Passwords don't match",
    "auth.backToLogin": "Back to login",
    "auth.preparingReset": "Preparing password reset...",
    "auth.sessionError": "Error setting up session. Please try the reset link again.",
    "auth.resetLinkInvalidTitle": "Link Invalid or Expired",
    "auth.resetLinkInvalidBody": "This reset link is no longer valid. It may have expired or already been used.",
    "auth.requestNewResetLink": "Request New Link",
    // Portal
    "portal.title": "Student Portal",
    "portal.noAccess": "Access Denied",
    "portal.accessDescription": "You don't have access to this area. Please contact the administrator if you believe this is an error.",
    "portal.lessons": "Lessons",
    "portal.noLessons": "No lessons available yet",
    "portal.video": "Video",
    "portal.videos": "Videos",
    "portal.exercise": "Exercise",
    "portal.presentation": "Presentation",
    "portal.files": "Files",
    "portal.download": "Download",
    "portal.downloadError": "Error downloading file",
    "portal.watch": "Watch",
    "portal.back": "Back",
    "portal.lessonNotFound": "Lesson not found",
    "portal.noVideos": "No videos available",
    "portal.noFiles": "No files available",
    "portal.qa": "Q&A",
    "portal.askQuestion": "Ask a Question",
    "portal.questionPlaceholder": "Type your question here...",
    "portal.questionPrivate": "Private question (only admin sees)",
    "portal.questionPublic": "Public question (visible to all)",
    "portal.submit": "Submit",
    "portal.questionSubmitted": "Question submitted successfully",
    "portal.questionError": "Error submitting question",
    "portal.noQuestions": "No questions yet",
    "portal.answered": "Answered",
    "portal.noAnswer": "Not answered yet",
    "portal.public": "Public",
    "portal.private": "Private",
    "portal.admin.title": "Portal Management",
    "portal.admin.addLesson": "Add Lesson",
    "portal.admin.description": "Description",
    "portal.admin.descriptionPlaceholder": "Enter lesson description...",
    "portal.admin.lessonAdded": "Lesson added successfully",
    "portal.admin.lessonError": "Error adding lesson",
    "portal.admin.existingLessons": "Existing Lessons",
    "portal.admin.lessonDeleted": "Lesson deleted",
    "portal.admin.deleteError": "Error deleting",
    "portal.admin.uploadFile": "Upload File",
    "portal.admin.selectLesson": "Select Lesson",
    "portal.admin.selectLessonPlaceholder": "Choose a lesson...",
    "portal.admin.fileType": "File Type",
    "portal.admin.selectFile": "Select File",
    "portal.admin.uploading": "Uploading...",
    "portal.admin.fileUploaded": "File uploaded successfully",
    "portal.admin.fileError": "Error uploading file",
    "portal.admin.unanswered": "unanswered",
    "portal.admin.yourAnswer": "Your answer",
    "portal.admin.answerPlaceholder": "Type your answer...",
    "portal.admin.answer": "Answer",
    "portal.admin.answerSaved": "Answer saved",
    "portal.admin.answerError": "Error saving answer",
    "portal.admin.addResource": "Add",
    "portal.admin.addVideo": "Add Recording",
    "portal.admin.addPresentation": "Add Presentation",
    "portal.admin.addWorksheet": "Add Worksheet",
    "portal.admin.presentations": "Presentations",
    "portal.admin.worksheets": "Worksheets",
    "portal.admin.noResources": "None yet",
    "portal.admin.resourceTitle": "Title",
    "portal.admin.dragToReorder": "Drag to reorder",
    "portal.admin.resourceDeleted": "Resource deleted",
    "portal.admin.orderUpdated": "Order updated",
    "portal.admin.videoSource": "Video source",
    "portal.admin.youtubeLink": "YouTube link",
    "portal.admin.vimeoLink": "Vimeo link",
    "portal.admin.zoomLink": "Zoom recording",
    "portal.admin.enterUrl": "Enter link",
    "portal.admin.invalidUrl": "Invalid link",
    "portal.admin.validUrl": "Valid link",
    "portal.openRecording": "Open Recording",
    "portal.zoomRecording": "Zoom Recording",
    "portal.zoomRecordingMessage": "Zoom recordings open in a new window",
    "portal.invalidVideoUrl": "Invalid video URL",

    // Media Library
    "media.title": "Media Library",
    "media.upload": "Upload New",
    "media.search": "Search...",
    "media.filterByType": "Filter by type",
    "media.allTypes": "All Types",
    "media.typeVideo": "Video",
    "media.typeDocument": "Document",
    "media.typePresentation": "Presentation",
    "media.typeAudio": "Audio",
    "media.typeLink": "Link",
    "media.noMedia": "No media yet",
    "media.columnTitle": "Title",
    "media.columnType": "Type",
    "media.columnSource": "Source",
    "media.columnDuration": "Duration",
    "media.columnUsage": "Usage",
    "media.columnActions": "Actions",
    "media.sourceFile": "File",
    "media.usedInLessons": "In {count} lessons",
    "media.usedInLessonsLabel": "Used in lessons",
    "media.deleteConfirm": "Delete Media?",
    "media.deleteWarning": "This action cannot be undone.",
    "media.deleteWarningUsed": "This media is used in {count} lessons. Deleting it will remove it from all lessons.",
    "media.edit": "Edit Media",
    "media.description": "Description",
    "media.descriptionPlaceholder": "Add notes about this media (admin only)...",
    "media.selectFromLibrary": "Select from Library",
    "media.uploadNew": "Upload New",
    "media.addToLesson": "Add to Lesson",
    "media.addedToLesson": "Added to lesson",
    "media.removeFromLesson": "Remove from lesson",
    "media.removedFromLesson": "Removed from lesson",
    "media.selectedCount": "{count} selected",
  },
  he: {
    // Header
    "nav.home": "בית",
    "nav.about": "אודות",
    "nav.bots": "עוזרי AI",
    "nav.contact": "צור קשר",
    "nav.contents": "תכנים",
    "nav.portal": "אזור תלמידים",
    "nav.login": "התחברות",
    "nav.logout": "התנתקות",
    "nav.dashboard": "דשבורד",

    // Dashboard
    "dashboard.welcome": "ברוכה הבאה!",
    "dashboard.subtitle": "עקבי אחרי ההתקדמות שלך והמשיכי ללמוד",
    "dashboard.myProgress": "ההתקדמות שלי",
    "dashboard.totalLessons": "סה״כ שיעורים",
    "dashboard.watchedLessons": "הושלמו",
    "dashboard.remainingLessons": "נותרו",
    "dashboard.nextStep": "הצעד הבא שלך",
    "dashboard.continue": "המשיכי",
    "dashboard.allCompleted": "כל השיעורים הושלמו!",
    "dashboard.congratulations": "עבודה מדהימה! סיימת את כל הקורס.",
    "dashboard.myLessons": "השיעורים שלי",
    "dashboard.lesson": "שיעור",
    "dashboard.admin.title": "סטטיסטיקות כלליות",
    "dashboard.admin.totalUsers": "סה״כ משתמשים",
    "dashboard.admin.activeUsers": "פעילים (7 ימים)",
    "dashboard.admin.completionRate": "אחוז השלמה",
    "dashboard.admin.progressByLesson": "התקדמות לפי שיעור",
    "dashboard.admin.recentUsers": "משתמשים אחרונים",
    "dashboard.admin.user": "משתמש",
    "dashboard.admin.progress": "התקדמות",
    "dashboard.admin.lastActivity": "פעילות אחרונה",
    "dashboard.admin.noUsers": "אין משתמשים עדיין",
    "dashboard.admin.anonymous": "אנונימי",
    "dashboard.admin.previous": "הקודם",
    "dashboard.admin.next": "הבא",
    "dashboard.admin.page": "עמוד",

    // Hero
    "hero.title": "הדרך שלך לקליניקה יציבה ומבוקשת",
    "hero.subtitle": "איך ליצור קליניקה שמתאימה לך",
    "hero.cta": "קבלו חומרים בחינם",
    "hero.secondary_cta": "לראות איך זה עובד",

    // How It Works
    "howItWorks.label": "התהליך",
    "howItWorks.title": "הדרך שלך לקליניקה משגשגת",
    "howItWorks.subtitle": "ארבעה צעדים פשוטים לשינוי הקליניקה שלך",
    "howItWorks.step1.title": "הרשמה",
    "howItWorks.step1.desc": "צרו חשבון וקבלו גישה מיידית לכל חומרי הלמידה",
    "howItWorks.step2.title": "למידה",
    "howItWorks.step2.desc": "צפו בשיעורי וידאו והשלימו תרגילים מעשיים בקצב שלכם",
    "howItWorks.step3.title": "תמיכה",
    "howItWorks.step3.desc": "שאלו שאלות וקבלו הדרכה אישית מהמומחים שלנו",
    "howItWorks.step4.title": "צמיחה",
    "howItWorks.step4.desc": "יישמו את מה שלמדתם וראו את הקליניקה משגשגת",

    // Benefits
    "benefits.label": "למה לבחור בנו",
    "benefits.title": "צמחו בפרקטיקה, הישארו נאמנים לעצמכם",
    "benefits.subtitle": "הגישה שלנו עוזרת לפסיכותרפיסטים למשוך לקוחות אידיאליים תוך כיבוד הערכים הטיפוליים שלהם",
    "benefits.item1.title": "מצאו את הנישה שלכם",
    "benefits.item1.desc": "גלו מה מייחד את הפרקטיקה שלכם ומושך לקוחות שמתחברים באמת לגישה שלכם",
    "benefits.item2.title": "שיווק אותנטי",
    "benefits.item2.desc": "למדו אסטרטגיות שיווק שמרגישות טבעיות ומתאימות לאתיקה המקצועית שלכם",
    "benefits.item3.title": "צמיחה בת-קיימא",
    "benefits.item3.desc": "בנו פרקטיקה יציבה עם זרימת לקוחות עקבית ללא שחיקה או עומס",

    // Testimonials
    "testimonials.label": "סיפורי הצלחה",
    "testimonials.title": "מה מטפלים אומרים",
    "testimonials.subtitle": "הצטרפו למאות מטפלים ששינו את הקליניקה שלהם",
    "testimonials.testimonial1.quote": "הקורס הזה שינה לחלוטין את הדרך שבה אני חושבת על שיווק הקליניקה שלי. סוף סוף אני מרגישה בטוחה לחשוף את עצמי.",
    "testimonials.testimonial1.name": "רחל כ.",
    "testimonials.testimonial1.role": "פסיכולוגית קלינית",
    "testimonials.testimonial2.quote": "העוזרים הדיגיטליים מדהימים. הם עזרו לי למצוא את הנישה שלי בשיחה אחת.",
    "testimonials.testimonial2.name": "מיכאל ש.",
    "testimonials.testimonial2.role": "מטפל זוגי ומשפחתי",
    "testimonials.testimonial3.quote": "עברתי מ-3 מטופלים בשבוע לקליניקה מלאה תוך חודשיים. ממליצה בחום!",
    "testimonials.testimonial3.name": "אליזה ל.",
    "testimonials.testimonial3.role": "מטפלת באמנות",

    // Features
    "features.label": "מה כלול",
    "features.title": "כל מה שצריך להצלחה",
    "features.subtitle": "כלים ומשאבים מקיפים שתוכננו למטפלים עסוקים",
    "features.videos.title": "שיעורי וידאו",
    "features.videos.desc": "20+ שעות תוכן",
    "features.exercises.title": "תרגילים מעשיים",
    "features.exercises.desc": "דפי עבודה מעשיים",
    "features.community.title": "גישה לקהילה",
    "features.community.desc": "התחברו עם עמיתים",
    "features.ai.title": "עוזרי AI",
    "features.ai.desc": "הדרכה 24/7",
    "features.support.title": "תמיכה אישית",
    "features.support.desc": "שאלות ותשובות מומחים",
    "features.mobile.title": "גישה לנייד",
    "features.mobile.desc": "למדו בכל מקום",

    // Bots
    "bots.title": "עוזרי AI למטפלים",
    "bots.subtitle": "כלים חכמים שתוכננו במיוחד לעזור לכם לצמוח בפרקטיקה",
    "bots.niche.title": "בוט מציאת נישה",
    "bots.niche.desc": "גלו את הנישה הטיפולית הייחודית שלכם ואת פרופיל הלקוח האידיאלי באמצעות חקירה מודרכת",
    "bots.strategy.title": "בוט תכנון אסטרטגיה",
    "bots.strategy.desc": "צרו אסטרטגיית שיווק מותאמת אישית שמתאימה לערכים ולזמן שלכם",
    "bots.content.title": "בוט יצירת תוכן",
    "bots.content.desc": "הפיקו רעיונות תוכן אותנטיים שמציגים את המומחיות שלכם ומושכים לקוחות",
    "bots.cta": "נסו עכשיו",
    "bots.teaser": "רוצים לגלות את העוזרים הדיגיטליים שלנו?",
    "bots.teaserLink": "למידע נוסף",

    // CTA
    "cta.title": "מוכנים לצמוח בפרקטיקה באופן אותנטי?",
    "cta.subtitle": "הצטרפו למאות מטפלים ששינו את הקליניקה שלהם עם השיטה המוכחת שלנו",
    "cta.button": "התחילו את המסע",
    "cta.secondaryButton": "למידע נוסף",

    // Form
    "form.title": "קבלו חומרי שיווק בחינם",
    "form.subtitle": "הצטרפו לקהילה שלנו וקבלו כלים מעשיים לצמיחה אותנטית בפרקטיקה",
    "form.name": "שם מלא",
    "form.email": "כתובת אימייל",
    "form.phone": "מספר נייד",
    "form.submit": "קבלו חומרים בחינם",
    "form.privacy": "אנחנו מכבדים את הפרטיות שלכם. ניתן לבטל בכל עת.",

    // Footer
    "footer.tagline": "מעצימים מטפלים לצמוח באותנטיות",
    "footer.rights": "כל הזכויות שמורות",

    // Contents
    "contents.title": "משאבים ומאמרים",
    "contents.subtitle": "תובנות וכלים שיעזרו לכם לצמוח בפרקטיקה",
    "contents.empty": "אין תכנים זמינים עדיין",
    "contents.readMore": "קראו עוד",
    "contents.back": "חזרה לתכנים",
    "contents.admin.add": "הוסף תוכן",
    "contents.admin.edit": "ערוך",
    "contents.admin.delete": "מחק",
    "contents.admin.cancel": "ביטול",
    "contents.admin.save": "שמור",
    "contents.admin.saving": "שומר...",
    "contents.admin.saveSuccess": "התוכן נשמר בהצלחה",
    "contents.admin.saveError": "שגיאה בשמירת התוכן",
    "contents.admin.deleteConfirm": "למחוק את התוכן?",
    "contents.admin.deleteWarning": "לא ניתן לבטל פעולה זו.",
    "contents.admin.deleteSuccess": "התוכן נמחק בהצלחה",
    "contents.admin.deleteError": "שגיאה במחיקת התוכן",
    "contents.form.title": "כותרת",
    "contents.form.titlePlaceholder": "הזינו כותרת...",
    "contents.form.content": "תוכן",
    "contents.form.contentPlaceholder": "הזינו תוכן...",
    "contents.form.language": "שפה",

    // Auth
    "auth.loginTitle": "ברוכים השבים",
    "auth.loginSubtitle": "התחברו לחשבון שלכם",
    "auth.signupTitle": "יצירת חשבון",
    "auth.signupSubtitle": "הצטרפו לקהילת המטפלים שלנו",
    "auth.email": "אימייל",
    "auth.password": "סיסמה",
    "auth.loginButton": "התחברות",
    "auth.signupButton": "יצירת חשבון",
    "auth.loading": "טוען...",
    "auth.noAccount": "אין לכם חשבון? הירשמו",
    "auth.hasAccount": "כבר יש לכם חשבון? התחברו",
    "auth.loginSuccess": "ברוכים השבים!",
    "auth.signupSuccess": "החשבון נוצר! בדקו את האימייל לאישור.",
    "auth.alreadyRegistered": "האימייל הזה כבר רשום",
    "auth.forgotPassword": "שכחת את הסיסמה?",
    "auth.forgotTitle": "איפוס סיסמה",
    "auth.forgotSubtitle": "הזינו את האימייל שלכם לקבלת קישור איפוס",
    "auth.sendResetLink": "שלח קישור איפוס",
    "auth.resetSent": "בדקו את האימייל לקבלת הקישור",
    "auth.resetTitle": "הגדרת סיסמה חדשה",
    "auth.resetSubtitle": "הזינו את הסיסמה החדשה שלכם",
    "auth.newPassword": "סיסמה חדשה",
    "auth.confirmPassword": "אישור סיסמה",
    "auth.updatePassword": "עדכון סיסמה",
    "auth.passwordUpdated": "הסיסמה עודכנה בהצלחה!",
    "auth.passwordMismatch": "הסיסמאות לא תואמות",
    "auth.backToLogin": "חזרה להתחברות",
    "auth.preparingReset": "מכינים את האפשרות לאיפוס סיסמה...",
    "auth.sessionError": "שגיאה בהגדרת הסשן. נסו את הקישור שוב.",
    "auth.resetLinkInvalidTitle": "הקישור לא תקין או פג תוקף",
    "auth.resetLinkInvalidBody": "קישור האיפוס כבר לא בתוקף. ייתכן שפג תוקפו או שכבר נוצל.",
    "auth.requestNewResetLink": "בקש קישור חדש",

    // Portal
    "portal.title": "אזור התלמידים",
    "portal.noAccess": "אין גישה",
    "portal.accessDescription": "אין לך גישה לאזור זה. אנא פנה למנהל אם אתה מאמין שזו שגיאה.",
    "portal.lessons": "שיעורים",
    "portal.noLessons": "אין שיעורים עדיין",
    "portal.video": "וידאו",
    "portal.videos": "הקלטות וידאו",
    "portal.exercise": "תרגיל",
    "portal.presentation": "מצגת",
    "portal.files": "קבצים",
    "portal.download": "הורד",
    "portal.downloadError": "שגיאה בהורדת הקובץ",
    "portal.watch": "צפה",
    "portal.back": "חזרה",
    "portal.lessonNotFound": "השיעור לא נמצא",
    "portal.noVideos": "אין הקלטות וידאו",
    "portal.noFiles": "אין קבצים",
    "portal.qa": "שאלות ותשובות",
    "portal.askQuestion": "שאל שאלה",
    "portal.questionPlaceholder": "כתוב את השאלה שלך כאן...",
    "portal.questionPrivate": "שאלה פרטית (רק האדמין רואה)",
    "portal.questionPublic": "שאלה ציבורית (גלויה לכולם)",
    "portal.submit": "שלח",
    "portal.questionSubmitted": "השאלה נשלחה בהצלחה",
    "portal.questionError": "שגיאה בשליחת השאלה",
    "portal.noQuestions": "אין שאלות עדיין",
    "portal.answered": "נענתה",
    "portal.noAnswer": "טרם נענתה",
    "portal.public": "ציבורי",
    "portal.private": "פרטי",
    "portal.admin.title": "ניהול אזור תלמידים",
    "portal.admin.addLesson": "הוסף שיעור",
    "portal.admin.description": "תיאור",
    "portal.admin.descriptionPlaceholder": "הזן תיאור לשיעור...",
    "portal.admin.lessonAdded": "השיעור נוסף בהצלחה",
    "portal.admin.lessonError": "שגיאה בהוספת שיעור",
    "portal.admin.existingLessons": "שיעורים קיימים",
    "portal.admin.lessonDeleted": "השיעור נמחק",
    "portal.admin.deleteError": "שגיאה במחיקה",
    "portal.admin.uploadFile": "העלה קובץ",
    "portal.admin.selectLesson": "בחר שיעור",
    "portal.admin.selectLessonPlaceholder": "בחר שיעור...",
    "portal.admin.fileType": "סוג קובץ",
    "portal.admin.selectFile": "בחר קובץ",
    "portal.admin.uploading": "מעלה...",
    "portal.admin.fileUploaded": "הקובץ הועלה בהצלחה",
    "portal.admin.fileError": "שגיאה בהעלאת הקובץ",
    "portal.admin.unanswered": "ללא תשובה",
    "portal.admin.yourAnswer": "תשובתך",
    "portal.admin.answerPlaceholder": "כתוב את התשובה שלך...",
    "portal.admin.answer": "ענה",
    "portal.admin.answerSaved": "התשובה נשמרה",
    "portal.admin.answerError": "שגיאה בשמירת התשובה",
    "portal.admin.addResource": "הוסף",
    "portal.admin.addVideo": "הוסף הקלטה",
    "portal.admin.addPresentation": "הוסף מצגת",
    "portal.admin.addWorksheet": "הוסף דף עבודה",
    "portal.admin.presentations": "מצגות",
    "portal.admin.worksheets": "דפי עבודה",
    "portal.admin.noResources": "אין עדיין",
    "portal.admin.resourceTitle": "כותרת",
    "portal.admin.dragToReorder": "גרור לשינוי סדר",
    "portal.admin.resourceDeleted": "המשאב נמחק",
    "portal.admin.orderUpdated": "הסדר עודכן",
    "portal.admin.videoSource": "מקור הוידאו",
    "portal.admin.youtubeLink": "קישור YouTube",
    "portal.admin.vimeoLink": "קישור Vimeo",
    "portal.admin.zoomLink": "הקלטת Zoom",
    "portal.admin.enterUrl": "הכניסי קישור",
    "portal.admin.invalidUrl": "קישור לא תקין",
    "portal.admin.validUrl": "קישור תקין",
    "portal.openRecording": "פתח הקלטה",
    "portal.zoomRecording": "הקלטת Zoom",
    "portal.zoomRecordingMessage": "הקלטות Zoom נפתחות בחלון חדש",
    "portal.invalidVideoUrl": "קישור וידאו לא תקין",

    // Media Library
    "media.title": "ספריית מדיה",
    "media.upload": "העלה חדש",
    "media.search": "חיפוש...",
    "media.filterByType": "סנן לפי סוג",
    "media.allTypes": "כל הסוגים",
    "media.typeVideo": "וידאו",
    "media.typeDocument": "מסמך",
    "media.typePresentation": "מצגת",
    "media.typeAudio": "אודיו",
    "media.typeLink": "לינק",
    "media.noMedia": "אין מדיה עדיין",
    "media.columnTitle": "כותרת",
    "media.columnType": "סוג",
    "media.columnSource": "מקור",
    "media.columnDuration": "אורך",
    "media.columnUsage": "שימוש",
    "media.columnActions": "פעולות",
    "media.sourceFile": "קובץ",
    "media.usedInLessons": "ב-{count} שיעורים",
    "media.usedInLessonsLabel": "נמצא בשיעורים",
    "media.deleteConfirm": "למחוק מדיה?",
    "media.deleteWarning": "לא ניתן לבטל פעולה זו.",
    "media.deleteWarningUsed": "המדיה בשימוש ב-{count} שיעורים. מחיקה תסיר אותה מכל השיעורים.",
    "media.edit": "עריכת מדיה",
    "media.description": "תיאור",
    "media.descriptionPlaceholder": "הוסף הערות על מדיה זו (לאדמין בלבד)...",
    "media.selectFromLibrary": "בחר מהספרייה",
    "media.uploadNew": "העלה חדש",
    "media.addToLesson": "הוסף לשיעור",
    "media.addedToLesson": "נוסף לשיעור",
    "media.removeFromLesson": "הסר משיעור",
    "media.removedFromLesson": "הוסר מהשיעור",
    "media.selectedCount": "{count} נבחרו",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === "he";

  return <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
